update

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -29,7 +29,7 @@ jobs:
       with:
         cmd: install
     - name: test backstop
-      run: ./node_modules/.bin/backstop test && echo 'passed' || echo 'failed'
-      run: ./node_modules/.bin/backstop test --approve
+      run: ./node_modules/.bin/backstop test && echo 'passed' || echo 'failed' 
+      ./node_modules/.bin/backstop test --approve
       run: ./node_modules/.bin/backstop test
       
